### ISSUE TITLE
Missing integration logo in frontend.

### ISSUE THREAD

**Issue by Midifreakz** [SDR3078/ps3-home-assistant#13]
Hi SDR3078,

Since i'm a graphic designer I have designed some icons for your integration.
I have made them in analogy with the official PS4 integration. 
They are formatted and named as per official HASS instructions.

![dark_icon](https://github.com/SDR3078/ps3-home-assistant/assets/9931131/ab6e5ea0-6ddb-4ab0-9615-b5e2c459753e)

You can download them here: 
https://www.dropbox.com/scl/fo/csprd0r1ryscwh661tpke/AEPku9F9_fbiyEkHSF4B3rE?rlkey=qflz3mbtu3g36mxzld44qe12c&dl=0

You'll need to add them to the HASS brand reposity somehow, but it's not really clear to me how to do that.

You can find more info here
https://developers.home-assistant.io/blog/2020/05/08/logos-custom-integrations/

**Comment by SDR3078** [comment]
Hi @Midifreakz , thanks for your

**Comment by Midifreakz** [comment]
Hi, oh thats a pitty but understandable, feel free to drop his feedback here and i’ll check to make something suitable
