### ISSUE TITLE
Device becomes unavailable when Physical PS3 is turned OFF. 

### ISSUE THREAD

**Issue by Midifreakz** [SDR3078/ps3-home-assistant#16]
Hi SDR3078,

Hope you are doing well.

I have noticed that when the PS3 is off for a while, the entire PS3 device becomes unavailable. 
This makes it impossible to turn the ps3 back on from Home Assistant. You might want to look in to this. 

<img width="659" alt="Screenshot 2024-06-26 at 08 02 26" src="https://github.com/SDR3078/ps3-home-assistant/assets/9931131/a3f818c3-814d-4432-a915-85dfe70f75c0">

**Comment by SDR3078** [comment]
Hi @Midifreakz! Thanks for bringing this to my attention! Could you post the logs related to the ps3 integration from around when the entities became unavailable? This way it would be easier to define the root cause, thanks!

**Comment by Dante2202** [comment]
I am also getting this error, these are what my logs show:
![error1](https://github.com/SDR3078/ps3-home-assistant/assets/101029157/4ecf1680-9c4d-4b1e-a1e8-547e4dd371e1)
![error2](https://github.com/SDR3078/ps3-home-assistant/assets/101029157/69ad8e09-0b3b-4536-94c7-cf4d872e07f0)
![error3](https://github.com/SDR3078/ps3-home-assistant/assets/101029157/53232c70-53e6-4bf5-a1a5-941bf081397a)

**Comment by SDR3078** [comment]
@Dante2202 could you open another issue for this? From the logs, it seems unrelated to the above mentioned issue.

**Comment by Dante2202** [comment]
Sure I can open a new issue I just figured these were related to this issue because I am getting the same exact issue as the original post.

**Comment by SDR3078** [comment]
Aha ok, my apologies! It seems like for some reason, no data is returned for the ps3 firmware. Does it help to delete your device, and reconfigure the integration?

**Comment by Dante2202** [comment]
I deleted my device and integration then re added everything and so far I have not gotten that error again.

**Comment by Dante2202** [comment]
Looks like after a while the error comes back:
![Screenshot 2024-07-08 150050](https://github.com/SDR3078/ps3-home-assistant/assets/101029157/8ff46b4b-6f9d-4848-b1cb-6e343c67b3fe)

**Comment by SDR3078** [comment]
Hi @Dante2202 , I am not able to replicate this error so unfortunately I cannot fix it for now.

@Midifreakz I was able to reproduce the original error and it might have to do with an error on the server side of the integration where webMAN stops responding, not even to calls made outside of the integration. Normally turning the PlayStation on and off should help. I will leave the issue open for a bit more time in case there is more occurrences.

**Comment by SDR3078** [comment]
@Dante2202, is it possible to open webMAN through an unrelated browser? You can check https://github.com/aldostools/webMAN-MOD/wiki/Web-Commands for the commands.

**Comment by Midifreakz** [comment]
Hi @SDR3078 

I have installed the integration freshly through HACS yesterday (The Main Branch was latest I presume?)
Unfortunately the issue persists. I have enable debug logging in the integration pane (the red bug icon).

Not sure how to provide you with logs tho. Are the events you are looking for logged in system settings > system > logs? 

Grts

**Comment by SDR3078** [comment]
@Midifreakz, yes that would be great! If you could send me everything related to the PS3 integration, thanks!

**Comment by SDR3078** [comment]
I fixed the issue. The library that was used to make connections with the PS3 throws a couple of errors when it cannot connect (when the PS3 is off). Normally I caught them in an exception to report the off status, but I forgot to catch the aiohttp.client_exceptions.ClientConnectorError, which made it not recognize the status. This is fixed as of now in main. I will soon prepare a new release.

**Comment by Midifreakz** [comment]
Hi @SDR3078 

I usually got the problem after a HASS restart. It indeed seems to be fixed now! 
I will keep an eye on it for the next few days. 

Good job!
