### ISSUE TITLE
"Expected str" when adding

### ISSUE THREAD

**Issue by Dante2202** [SDR3078/ps3-home-assistant#17]
Looks like you posted this in the HA forum as well, I am getting the same error when trying to set this up.
![ccdff38801690bc6245e60d21365a0e337dc81bb](https://github.com/SDR3078/ps3-home-assistant/assets/101029157/bc2ba9d4-52c0-4d2b-9c54-9054184f3136)

I have added the ps3 folder to my custom_componenets folder inside my config folder but I cannot select a script or get past this page.

**Comment by SDR3078** [comment]
Hi! I indeed did not fix this yet, currently working on it!

**Comment by SDR3078** [comment]
@Dante2202 , can you check out the code in branch https://github.com/SDR3078/ps3-home-assistant/tree/bugfix_startup_script? If it's fixed there, I will merge it to main

**Comment by Dante2202** [comment]
If I added this through HACS in home assistant how do I make sure the new branch is added that includes this fix?

**Comment by Dante2202** [comment]
I tried adding it through HACS in the custom repository "https://github.com/SDR3078/ps3-home-assistant/tree/bugfix_startup_script" but I can't, it gives me the error "Repository 'sdr3078/ps3-home-assistant' exists in the store."

**Comment by Dante2202** [comment]
Maybe I am doing something wrong but I cannot get the bugfix to download within HACS.  I decided to manually edited the "config_flow.py" file and changed the line `(TURN_ON_SCRIPT, default = None)` to `(TURN_ON_SCRIPT)` and can confirm that the change did allow me to continue and add my PS3.

**Comment by SDR3078** [comment]
Hi @Dante2202, you can just change the branch to bugfix_startup_script on github, and then download the code as zip. Following that, you just copy that code in your custom integrations folder. Then you start up Home Assistant again and you should be able to use that version. Let me know if it works!
